# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registered_users',
            name='birth_date',
        ),
    ]
