# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_remove_userratings_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userratings',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
