# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_remove_userratings_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='thing',
            field=models.IntegerField(default=930201, unique=True),
            preserve_default=False,
        ),
    ]
