# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_userinfo_thing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='thing',
        ),
    ]
