# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 01:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20170712_0220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='picture',
            new_name='profile_pic',
        ),
    ]
