# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20170713_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='profile_pic',
        ),
    ]
